#!/usr/bin/env bash
#
# Rebuild the `deploy` branch from current `master` + concrete image tags.
#
# Inputs (env vars; unset ones are read from existing deploy-branch state,
# then default to "latest" if no prior state exists):
#   OMNIGENT_VENDOR_TAG
#
# Behavior:
#   1. Loads any existing image-tags.env from origin/deploy, per-key only
#      where the caller hasn't already supplied a value.
#   2. Force-creates a fresh `deploy` branch at master HEAD.
#   3. Writes image-tags.env recording the final pinned tags.
#   4. Sed-rewrites docker-compose.yml so the `:latest` placeholder
#      becomes `:<pinned-tag>`.
#   5. Commits and force-pushes deploy.
#
set -euo pipefail

# --- 1. Hydrate from existing deploy-branch state (without clobbering caller).
git fetch origin deploy 2>/dev/null || true
if git rev-parse --verify origin/deploy >/dev/null 2>&1; then
    EXISTING="$(git show origin/deploy:image-tags.env 2>/dev/null || true)"
    if [ -n "$EXISTING" ]; then
        while IFS='=' read -r key value; do
            case "$key" in
                ''|'#'*) continue ;;
            esac
            current="$(eval "echo \${$key:-__unset__}")"
            if [ "$current" = "__unset__" ]; then
                export "$key=$value"
            fi
        done <<<"$EXISTING"
    fi
fi

# --- 2. Final fallback.
: "${OMNIGENT_VENDOR_TAG:=latest}"

echo "Pinning deploy branch to:"
echo "  omnigent-server-vendor = $OMNIGENT_VENDOR_TAG"

# --- 3. Materialize the deploy branch at master HEAD.
git config user.name  "GitHub Actions Bot"
git config user.email "actions@github.com"
git checkout -B deploy

# --- 4. Write the recorded state.
cat >image-tags.env <<EOF
# Auto-generated by .github/scripts/build-deploy-branch.sh.
# Records the concrete GHCR tag this deploy branch's docker-compose.yml
# is pinned to. Each workflow run reads the prior state, overrides only the
# tags it produced, and rewrites this file + docker-compose.yml.
OMNIGENT_VENDOR_TAG=$OMNIGENT_VENDOR_TAG
EOF

# --- 5. Pin docker-compose.yml. Matches only the `:latest` placeholder from
#        master; a manually pinned compose is left alone.
sed -i \
    -e "s|omnigent-server-vendor:latest|omnigent-server-vendor:$OMNIGENT_VENDOR_TAG|g" \
    docker-compose.yml

# --- 6. Commit + force-push.
git add image-tags.env docker-compose.yml
if git diff --cached --quiet; then
    echo "No changes to deploy branch — pushing anyway to retrigger Portainer."
fi
git commit --allow-empty -m "pin: omnigent-server=$OMNIGENT_VENDOR_TAG"
git push origin deploy --force
